# Generated by Django 4.1.7 on 2023-05-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=10)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UWEflix.club')),
            ],
        ),
    ]
