# Generated by Django 4.1.7 on 2023-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UWEflix", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="age",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="seat_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="seats",
        ),
        migrations.AddField(
            model_name="booking",
            name="card_cvc",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="card_expire_month",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="card_expire_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="card_holder",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="card_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket_type",
            field=models.CharField(max_length=7),
        ),
    ]
