# Generated by Django 4.1.7 on 2023-05-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchasehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClubPurchaseHistory',
        ),
        migrations.DeleteModel(
            name='UserPurchaseHistory',
        ),
    ]
