# Generated by Django 4.1.7 on 2023-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix', '0002_representitive_user_userpurchasehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
